apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: test
spec:
  hard:
    requests.cpu: "2" # Total CPU requests allowed in the namespace
    limits.cpu: "3" # Total CPU limit across all pods
    requests.memory: "2Gi" # Total memory requests allowed
    limits.memory: "3Gi" # Total memory limit across all pods
    pods: "2" # Max number of Pods in this namespace
