apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: dev-team
spec:
  hard:
    requests.cpu: "4" # Total CPU requests allowed in the namespace
    limits.cpu: "8" # Total CPU limit across all pods
    requests.memory: "8Gi" # Total memory requests allowed
    limits.memory: "16Gi" # Total memory limit across all pods
    pods: "10" # Max number of Pods in this namespace
