apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: preferred-soft
  name: preferred-soft
spec:
  replicas: 6
  selector:
    matchLabels:
      run: preferred-soft
  template:
    metadata:
      labels:
        run: preferred-soft
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 40
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - node01
          - weight: 30
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - node02
          - weight: 30
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - node03
      containers:
      - image: nginx:latest
        name: preferred-soft
