apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: nginx:latest
        name: nginx
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "node01"
        effect: "NoSchedule"
